version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      USERNAME: root
      PASSWORD: example
    networks:
      - mongo_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradio
    ports:
      - 7860:7860
    depends_on:
      - api
    networks:
      - mongo_network
    command: python gradio_app.py

networks:
  mongo_network:
