[project]
name = "didactic-carnival"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.5",
    "gradio>=5.6.0",
    "pydantic-settings>=2.6.1",
    "pymongo>=4.10.1",
    "uvicorn>=0.32.0",
]
